#!/usr/bin/env ruby

# setting
browser_cmd = 'xdg-open'
clipboard_cmd = 'xclip'
album = 'Instant Upload'

require 'net/http'

# get id
idfile = ENV['HOME'] + "/.gyazo.id"

id = ''
if File.exist?(idfile) then
  id = File.read(idfile).chomp
end

# capture png file
tmpfile = "/tmp/image_upload#{$$}.png"
imagefile = ARGV[0]

if imagefile && File.exist?(imagefile) then
  system "convert '#{imagefile}' '#{tmpfile}'"
else
  system "import '#{tmpfile}'"
end

if !File.exist?(tmpfile) then
  exit
end

# upload
`google picasa post --title '#{album}' #{tmpfile}`
url = `google picasa list --title '#{album}'| grep ^image_upload#{$$}.png, | cut -f2 -d,`

puts url
if system "which #{clipboard_cmd} >/dev/null 2>&1" then
  system "echo -n '#{url}' | #{clipboard_cmd}"
end
system "#{browser_cmd} '#{url}'"

